# devlog 2024-08-28

_author: Trevor Johnson_

Demonstration of NPY and NPZ numpy ADRIOs.

In [1]:
# save a simple array to an .npy file and load it back using an adrio
from pathlib import Path

import numpy as np

from epymorph.adrio.numpy import NPY

array = np.array([1, 2, 3])
np.save('./scratch/npy_test.npy', arr=array)

adrio = NPY(Path('./scratch/npy_test.npy'))
print(adrio.evaluate())

[1 2 3]


In [2]:
# save multiple arrays to an .npz file and load them back individually using adrios
from epymorph.adrio.numpy import NPZ

array2 = np.array([4, 5, 6])
np.savez('./scratch/npz_test.npz', arr=array, arr2=array2)

adrio = NPZ(Path('./scratch/npz_test.npz'), 'arr')
# this adrio slices the array to exclude the fist element
adrio2 = NPZ(Path('./scratch/npz_test.npz'), 'arr2', [slice(1, 3)])

print(adrio.evaluate())
print(adrio2.evaluate())

[1 2 3]
[5 6]


In [3]:
# save and load a multidimensional array
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np.savez('./scratch/npz_test2.npz', array)

# slice each axis of the array individually
adrio = NPZ(Path('./scratch/npz_test2.npz'), 'arr_0', [slice(0, 2), slice(1, 3)])

print(adrio.evaluate())

[[2 3]
 [5 6]]
